### ISSUE TITLE
Question: Trigger animation when in viewport?

### ISSUE THREAD

**Issue by joncreative** [rough-stuff/rough-notation#44]
Preet, this library is money. Thanks for it. Using and quite happy.

Question: How would I go about triggering the notation when element is within viewport? 

Thanks ahead of time for your work on this tool; from a UX perspective, it speaks volumes for calling attention without breaking focus with the "F-Pattern" of scannability 👌

**Comment by pshihn** [comment]
Thanks!

To answer your question, IntersectionObserver would be the way to go about it, imo. 
The intersectionObserver callback will be called when the element comes into view, at which point you can call `show()` on the annotation.

**Comment by joncreative** [comment]
Will try this. 

Good stuff Preet. Keep rocking bro
